import type { Locale } from "@/lib/i18n/types";

export type LegalSection = {
  heading: string;
  paragraphs: string[];
  list?: string[];
};

export type LegalDoc = {
  title: string;
  effectiveLabel: string;
  effectiveDate: string;
  intro: string[];
  sections: LegalSection[];
  contactLabel: string;
  contactEmail: string;
};

export const LEGAL_CONTACT_EMAIL = "support@11s.io";
export const LEGAL_EFFECTIVE_DATE_EN = "August 8, 2026";
export const LEGAL_EFFECTIVE_DATE_ZH = "2026 年 8 月 8 日";

const termsEn: LegalDoc = {
  title: "Terms of Service",
  effectiveLabel: "Effective date",
  effectiveDate: LEGAL_EFFECTIVE_DATE_EN,
  intro: [
    "These Terms of Service (\"Terms\") govern your access to and use of 11s (the \"Service\"), a personal workspace for preparing and remembering one-on-one conversations, operated by the 11s team (\"we\", \"us\", \"our\").",
    "By creating an account or using the Service, you agree to these Terms. If you do not agree, do not use the Service. If you use the Service on behalf of an organization, you represent that you have authority to bind that organization, and \"you\" includes that organization.",
  ],
  sections: [
    {
      heading: "1. The Service",
      paragraphs: [
        "11s helps you keep notes, discussion history, curated talking points, and preparation ideas for your recurring one-on-one conversations, and can generate suggested talking points using artificial intelligence based on the context you provide. Sensitive workspace content is encrypted at rest (AES-256-GCM), and you can export or permanently delete your data at any time from the account page.",
        "The Service is a productivity and memory aid. It does not provide professional, legal, medical, psychological, financial, or human-resources advice, and it is not a system of record for employment decisions.",
      ],
    },
    {
      heading: "2. Eligibility",
      paragraphs: [
        "You must be at least 18 years old (or the age of majority in your jurisdiction, if higher) and capable of forming a binding contract to use the Service. The Service is not directed at children, and you may not use it to store information about children.",
      ],
    },
    {
      heading: "3. Your account",
      paragraphs: [
        "You are responsible for keeping your sign-in credentials confidential and for all activity under your account. Notify us promptly if you suspect unauthorized access. We are not liable for losses caused by your failure to protect your credentials.",
        "You must provide a valid email address and keep it current so we can reach you about security and billing matters.",
      ],
    },
    {
      heading: "4. Your content",
      paragraphs: [
        "You retain all rights to the content you enter into the Service, including names, notes, conversation summaries, and follow-ups (\"Your Content\"). You grant us a limited, non-exclusive, worldwide license to host, store, process, transmit, and display Your Content solely to operate, maintain, and improve the Service for you.",
        "The Service is designed for information about other people you interact with, such as colleagues and friends. You represent and warrant that you have the right and any necessary permission to record and store that information, that you will inform those people where the law requires it, and that you will honor their requests regarding their information.",
        "You must not use the Service to store or process: (a) content that is unlawful, defamatory, harassing, or infringing; (b) government-issued identification numbers, financial account numbers, or similar high-risk identifiers; (c) special categories of personal data (such as health, biometric, genetic, or precise location data, or data about racial origin, political opinions, religious beliefs, or sexual orientation); or (d) malware or malicious code.",
        "We may remove content or suspend accounts that violate these rules.",
      ],
    },
    {
      heading: "5. AI-generated suggestions",
      paragraphs: [
        "Preparation ideas are generated by an AI model from the context you have saved. They may be incomplete, inaccurate, poorly timed, or otherwise unsuitable. They are suggestions, not instructions, and they are not professional advice of any kind.",
        "You are solely responsible for what you choose to say and do in your conversations and relationships, and for any decisions you make in reliance on, or informed by, the Service.",
      ],
    },
    {
      heading: "6. Plans, billing, and cancellation",
      paragraphs: [
        "The Service offers a free plan with usage limits (currently up to 20 people and 3 AI credits per day, renewed daily) and a paid plan (\"Pro\", currently unlimited people and 100 AI credits per day, renewed daily, offered monthly, quarterly, and yearly). An AI credit is spent each time fresh preparation is generated. We may change plan features and limits with reasonable notice; changes that materially reduce the value of a paid plan will not take effect for you until your next renewal.",
        "Paid subscriptions renew automatically at the start of each billing period until cancelled. Prices are shown at checkout, are exclusive of applicable taxes unless stated otherwise, and are processed by our payment provider. You authorize us to charge your chosen payment method on a recurring basis.",
        "You can cancel at any time through the billing portal linked from your workspace settings. Cancellation takes effect at the end of the current paid period; you keep access until then. Payments are non-refundable except where required by law.",
        "If a payment fails, we may retry it and may downgrade your account to the free plan after notice. If your account is downgraded while it exceeds free-plan limits, your existing content is preserved, but features above the free limits may become unavailable until you upgrade again or reduce usage.",
      ],
    },
    {
      heading: "7. Acceptable use",
      paragraphs: [
        "You must not misuse the Service, including by: probing or testing its vulnerabilities; interfering with its operation; scraping or harvesting data; reselling or sublicensing access; reverse engineering except where the law permits it; using it to violate any law or the rights of others; or exceeding rate limits or attempting to circumvent plan limits.",
      ],
    },
    {
      heading: "8. Third-party services",
      paragraphs: [
        "The Service relies on third-party providers for infrastructure, data storage, authentication, payment processing, and AI models. Their acts and omissions are governed by their own terms, and we are not responsible for their availability or performance, though we choose providers carefully and design the Service to limit what each provider can access.",
      ],
    },
    {
      heading: "9. Termination",
      paragraphs: [
        "You may stop using the Service and delete your account at any time directly from the account page, which permanently removes your content and cancels any active subscription; you may also contact us for help. We recommend exporting your data first (a JSON export is available on the account page). We may suspend or terminate access if you breach these Terms, if required by law, or if the Service is discontinued, in which case we will give reasonable notice and a chance to export your data where practicable.",
      ],
    },
    {
      heading: "10. Disclaimers",
      paragraphs: [
        "The Service is provided \"as is\" and \"as available\". To the maximum extent permitted by law, we disclaim all warranties, express or implied, including merchantability, fitness for a particular purpose, and non-infringement. We do not warrant that the Service will be uninterrupted, error-free, or that any content will be preserved without loss.",
      ],
    },
    {
      heading: "11. Limitation of liability",
      paragraphs: [
        "To the maximum extent permitted by law, we will not be liable for any indirect, incidental, special, consequential, or punitive damages, or for lost profits, revenues, data, goodwill, or business opportunities, arising out of or related to the Service.",
        "Our aggregate liability for all claims relating to the Service is limited to the greater of (a) the amounts you paid us for the Service in the twelve months before the event giving rise to the claim, or (b) US$100. Some jurisdictions do not allow these limits, in which case they apply to the fullest extent permitted.",
      ],
    },
    {
      heading: "12. Indemnification",
      paragraphs: [
        "You will defend and indemnify us against claims, damages, losses, and expenses (including reasonable legal fees) arising from Your Content, your misuse of the Service, or your breach of these Terms, including any claim by a person whose information you stored in the Service without a lawful basis.",
      ],
    },
    {
      heading: "13. Governing law and disputes",
      paragraphs: [
        "These Terms are governed by the laws of the Hong Kong Special Administrative Region, without regard to conflict-of-law rules. Before filing a claim, you agree to contact us and try to resolve the dispute informally for at least 30 days.",
        "The courts of Hong Kong have exclusive jurisdiction over disputes arising from these Terms or the Service, except that you may bring a claim in your local courts, and nothing in these Terms limits any consumer rights that cannot be waived under the law of your residence.",
      ],
    },
    {
      heading: "14. Changes to these Terms",
      paragraphs: [
        "We may update these Terms from time to time. We will post the updated version with a new effective date and, for material changes, give advance notice by email or in the Service. Continued use after the effective date means you accept the updated Terms.",
      ],
    },
    {
      heading: "15. General",
      paragraphs: [
        "These Terms are the entire agreement between you and us about the Service. If any part is found unenforceable, the rest remains in effect. Our failure to enforce a provision is not a waiver. You may not assign these Terms without our consent; we may assign them in connection with a merger, acquisition, or sale of assets.",
      ],
    },
  ],
  contactLabel: "Questions about these Terms",
  contactEmail: LEGAL_CONTACT_EMAIL,
};

const termsZh: LegalDoc = {
  title: "服務條款",
  effectiveLabel: "生效日期",
  effectiveDate: LEGAL_EFFECTIVE_DATE_ZH,
  intro: [
    "本《服務條款》(下稱「本條款」)規範你對 11s(下稱「本服務」)的存取與使用。本服務是一個用來準備與記錄一對一對話的個人工作區,由 11s 團隊(下稱「我們」)營運。",
    "只要你建立帳號或使用本服務,即表示你同意本條款;若不同意,請勿使用本服務。若你代表組織使用本服務,即表示你有權代表該組織同意本條款,且「你」同時包含該組織。",
  ],
  sections: [
    {
      heading: "1. 服務內容",
      paragraphs: [
        "11s 協助你為固定進行的一對一對話保存筆記、對話紀錄、你親自整理的談話重點與準備構想,並可依你提供的脈絡,以人工智慧產生建議話題。敏感的工作區內容會以 AES-256-GCM 加密儲存;你也可以隨時在帳號頁匯出或永久刪除你的資料。",
        "本服務是提升效率與記憶的輔助工具,不提供專業、法律、醫療、心理、財務或人力資源建議,也不是用來做成人事決策的正式紀錄系統。",
      ],
    },
    {
      heading: "2. 使用資格",
      paragraphs: [
        "你必須年滿 18 歲(或你所在司法管轄區規定的成年年齡,以較高者為準),並具有締約能力,才能使用本服務。本服務不以兒童為對象,你也不得使用本服務儲存兒童的資料。",
      ],
    },
    {
      heading: "3. 你的帳號",
      paragraphs: [
        "你有責任妥善保管登入憑證,並對帳號下的所有活動負責。若發現未經授權的存取,請立即通知我們。因你未妥善保管憑證所造成的損失,我們不負賠償責任。",
        "你必須提供有效的電子郵件地址並保持最新,以便我們就安全性與帳單事宜與你聯絡。",
      ],
    },
    {
      heading: "4. 你的內容",
      paragraphs: [
        "你對輸入本服務的內容(包括姓名、筆記、對話摘要與待追蹤事項,下稱「你的內容」)保留所有權利。你授權我們在提供、維護與改善本服務所需的範圍內,以有限、非專屬、全球性的方式託管、儲存、處理、傳輸與顯示你的內容。",
        "本服務的設計用途,是記錄與你往來的其他人(例如同事與朋友)的相關資訊。你聲明並保證:你有權且已取得必要許可來記錄與儲存這些資訊;在法律要求時,你會告知這些人;並且你會配合他們對其資料提出的請求。",
        "你不得使用本服務儲存或處理:(a) 違法、誹謗、騷擾或侵權的內容;(b) 政府核發的證件號碼、金融帳號等高風險識別資料;(c) 特殊類別的個人資料(例如健康、生物特徵、基因或精確位置資料,或涉及種族、政治立場、宗教信仰、性傾向的資料);或 (d) 惡意程式碼。",
        "若內容違反上述規定,我們得移除內容或暫停帳號。",
      ],
    },
    {
      heading: "5. AI 產生的建議",
      paragraphs: [
        "準備構想是由 AI 模型依據你保存的脈絡所產生,可能不完整、不正確、不合時宜或不適用。這些內容僅為建議而非指示,也不構成任何種類的專業建議。",
        "你在對話與關係中選擇說什麼、做什麼,以及是否參考本服務做成任何決定,都由你自行負責。",
      ],
    },
    {
      heading: "6. 方案、收費與取消",
      paragraphs: [
        "本服務提供有使用上限的免費方案,以及付費方案(下稱「Pro」)。我們得在合理通知後調整方案功能與上限;若變更對付費方案的價值造成重大減損,對你將延至下一個續約日才生效。",
        "付費訂閱會在每個計費週期開始時自動續約,直到你取消為止。價格以結帳頁面所示為準,除另有說明外不含適用稅捐,並由我們的金流服務商處理。你授權我們定期向你選定的付款方式收費。",
        "你可以隨時透過工作區設定中的帳單入口取消訂閱。取消於目前付費週期結束時生效,在此之前你仍可继续使用。除法律另有規定外,已付款項不予退費。",
        "若扣款失敗,我們可能重試扣款,並在通知後將你的帳號降為免費方案。降級時若你的使用量超過免費上限,既有內容會保留,但超出免費方案的功能可能暫停使用,直到你再次升級或降低使用量。",
      ],
    },
    {
      heading: "7. 合理使用",
      paragraphs: [
        "你不得濫用本服務,包括:探測或測試系統漏洞;干擾服務運作;爬取或蒐集資料;轉售或轉授權存取權;在法律允許範圍外進行逆向工程;用本服務違反法律或侵害他人權利;或超過速率上限、試圖規避方案上限。",
      ],
    },
    {
      heading: "8. 第三方服務",
      paragraphs: [
        "本服務仰賴第三方供應商提供基礎設施、資料儲存、身分驗證、金流處理與 AI 模型。該等供應商的作為與不作為受其自身條款規範;我們雖審慎選擇供應商,並在設計上限制各供應商可接觸的範圍,但不對其可用性或效能負責。",
      ],
    },
    {
      heading: "9. 終止",
      paragraphs: [
        "你可以隨時停止使用本服務,並聯絡我們刪除帳號。若你違反本條款、基於法律要求,或本服務停止營運,我們得暫停或終止你的存取權;屆時我們會給予合理通知,並在可行的範圍內讓你有機會匯出資料。",
      ],
    },
    {
      heading: "10. 免責聲明",
      paragraphs: [
        "本服務依「現狀」與「現有」提供。在法律允許的最大範圍內,我們排除所有明示或默示的保證,包括適售性、特定用途適用性與不侵權。我們不保證服務不會中斷、沒有錯誤,或任何內容都能永久保存而不遺失。",
      ],
    },
    {
      heading: "11. 責任限制",
      paragraphs: [
        "在法律允許的最大範圍內,對於因本服務所生或相關的間接、附帶、特殊、衍生性或懲罰性損害,或利潤、收入、資料、商譽或商業機會的損失,我們不負賠償責任。",
        "我們就本服務相關所有請求的累計賠償責任,以 (a) 在引發請求的事件發生前十二個月內你支付給我們的服務費用,或 (b) 100 美元,兩者中較高者為限。部分司法管轄區不允許此類限制,屆時在該地法律允許的最大範圍內適用。",
      ],
    },
    {
      heading: "12. 補償",
      paragraphs: [
        "對於因你的內容、你濫用本服務或你違反本條款所引起的請求、損害、損失與費用(包括合理的律師費用),你應為我們抗辯並補償我們;這包括你所儲存資料的事主,因你欠缺合法依據而提出的請求。",
      ],
    },
    {
      heading: "13. 準據法與爭議解決",
      paragraphs: [
        "本條款以香港特別行政區法律為準據法,不適用衝突法則。在提起訴訟前,你同意先聯絡我們,以至少 30 天的時間嘗試和平解決爭議。",
        "因本條款或本服務所生的爭議,由香港法院專屬管轄;但你仍得向居住地的法院提出請求,且本條款不限制依你居住地法律不得拋棄的消費者權利。",
      ],
    },
    {
      heading: "14. 條款變更",
      paragraphs: [
        "我們得不時更新本條款。更新後的版本會標示新的生效日期並公布於本服務;屬重大變更者,我們會事先以電子郵件或服務內通知。生效日期後繼續使用本服務,即表示你接受更新後的條款。",
      ],
    },
    {
      heading: "15. 一般條款",
      paragraphs: [
        "本條款構成你與我們之間關於本服務的完整合意。任一条款經認定無效,其餘部分仍然有效。我們未行使或延遲行使權利,不構成拋棄。未經我們同意,你不得轉讓本條款;我們則得因合併、收購或資產出售而轉讓。",
      ],
    },
  ],
  contactLabel: "對本條款有疑問",
  contactEmail: LEGAL_CONTACT_EMAIL,
};

const privacyEn: LegalDoc = {
  title: "Privacy Policy",
  effectiveLabel: "Effective date",
  effectiveDate: LEGAL_EFFECTIVE_DATE_EN,
  intro: [
    "This Privacy Policy explains what information 11s (\"we\", \"us\") collects when you use the Service, how we use it, who we share it with, and the choices and rights you have.",
    "11s is a private workspace for notes and preparation about your one-on-one conversations. Privacy is central to the product: by default, your workspace content is visible only to your account.",
  ],
  sections: [
    {
      heading: "1. Information we collect",
      paragraphs: ["We collect the following categories of information:"],
      list: [
        "Account data: your email address and authentication credentials (passwords are stored only as cryptographic hashes by our authentication provider).",
        "Workspace content: the people, roles, organizations, notes, conversation summaries, topics, follow-ups, talking points, and preparation ideas you enter or generate — which may include personal information about other people. Sensitive workspace content is encrypted at rest (AES-256-GCM) in addition to transport encryption.",
        "Preferences: your language choice and plan details.",
        "Billing data: your plan, subscription status, and payment-history references. Card numbers and full payment details are collected and stored by our payment processor, not by us.",
        "Technical data: standard server logs such as IP address, browser type, and timestamps, used for security and reliability.",
      ],
    },
    {
      heading: "2. How we use information",
      paragraphs: ["We use the information we collect to:"],
      list: [
        "Provide the Service: store your content, sync it across your devices, and keep it private to your account.",
        "Generate preparation suggestions at your request, using the context you saved for the relevant person.",
        "Process payments and manage your subscription.",
        "Secure the Service, prevent abuse, and debug issues.",
        "Communicate with you about your account, security, billing, and material product or policy changes.",
        "Comply with legal obligations.",
      ],
    },
    {
      heading: "3. AI processing",
      paragraphs: [
        "When you ask the Service to prepare suggestions, the relevant context (such as your notes and discussion history for that person) is sent to the AI model provider we use, which processes it solely to return suggestions to you. Our agreements with providers require that your content is not used to train their models.",
        "Please do not enter highly sensitive information into the Service (see our Terms of Service for prohibited content), whether or not you use AI features.",
      ],
    },
    {
      heading: "4. Legal bases (EEA, UK, and similar jurisdictions)",
      paragraphs: [
        "Where data-protection law requires a legal basis, we process personal data: (a) to perform our contract with you (providing the Service you signed up for); (b) based on our legitimate interests in securing and improving the Service, balanced against your rights; (c) with your consent, where requested; and (d) to comply with legal obligations.",
      ],
    },
    {
      heading: "5. How we share information",
      paragraphs: [
        "We do not sell your personal information. We share it only with:",
      ],
      list: [
        "Service providers who operate the Service for us: cloud hosting and database infrastructure, authentication, payment processing, and AI model providers. Each receives only what it needs to perform its function, under contractual confidentiality and data-protection obligations.",
        "Authorities or other parties where required by law, legal process, or to protect the rights, safety, and security of the Service, our users, or others.",
        "A successor in connection with a merger, acquisition, or sale of assets, subject to this Policy.",
      ],
    },
    {
      heading: "6. International transfers",
      paragraphs: [
        "We serve users worldwide, and our providers may process data in countries other than yours, including countries whose laws may differ. Where required, we rely on recognized safeguards such as standard contractual clauses for cross-border transfers.",
      ],
    },
    {
      heading: "7. Retention",
      paragraphs: [
        "We keep your account data and workspace content for as long as your account is active. When you delete content, it is removed from active systems promptly and from backups on their normal rotation cycle. When you delete your account — which you can do yourself from the account page — we delete your content and cancel any active paid subscription within a reasonable period, except where law requires longer retention (for example, payment records).",
      ],
    },
    {
      heading: "8. Security",
      paragraphs: [
        "We use encryption in transit and at rest, account-level isolation of workspace data, and least-privilege access controls. Sensitive workspace content (such as names, notes, talking points, and career information) is additionally encrypted at the application layer with AES-256-GCM before it is stored. No method of transmission or storage is perfectly secure; if we learn of a breach affecting your personal data, we will notify you and the authorities as the law requires.",
      ],
    },
    {
      heading: "9. Your rights",
      paragraphs: [
        "Depending on where you live (including the EEA, UK, California, and other jurisdictions), you may have rights to access, correct, export, or delete your personal data, to object to or restrict certain processing, and to withdraw consent. You can exercise most of these directly in the Service: view, edit, and delete content in the workspace, download a full JSON export of your data from the account page, or permanently delete your account (which removes all associated content) from the account page. You can also contact us at any time.",
        "You may also have the right to complain to your local data-protection authority. California residents: we do not sell or share personal information for cross-context behavioral advertising.",
      ],
    },
    {
      heading: "10. Information about other people",
      paragraphs: [
        "The Service lets you record information about people you know. For that information, you act as the data controller and we act as your processor: you decide what to record, and you are responsible for having a lawful basis, telling people where required, and responding to their requests. If someone asks us directly about information you stored about them, we may direct them to you or ask you to respond.",
      ],
    },
    {
      heading: "11. Cookies",
      paragraphs: [
        "We use only essential cookies and browser storage required to sign you in, keep your session secure, and remember your preferences. We do not use advertising or third-party tracking cookies.",
      ],
    },
    {
      heading: "12. Children",
      paragraphs: [
        "The Service is not directed at anyone under 18, and we do not knowingly collect personal information from children. If you believe a child has provided us information, contact us and we will delete it.",
      ],
    },
    {
      heading: "13. Changes to this Policy",
      paragraphs: [
        "We may update this Policy from time to time. We will post the updated version with a new effective date and, for material changes, give advance notice by email or in the Service.",
      ],
    },
  ],
  contactLabel: "Questions about privacy or your data",
  contactEmail: LEGAL_CONTACT_EMAIL,
};

const privacyZh: LegalDoc = {
  title: "隱私權政策",
  effectiveLabel: "生效日期",
  effectiveDate: LEGAL_EFFECTIVE_DATE_ZH,
  intro: [
    "本《隱私權政策》說明 11s(下稱「我們」)在你使用本服務時蒐集哪些資訊、如何使用、與誰分享,以及你擁有的選擇與權利。",
    "11s 是用來記錄與準備一對一對話的私人工作區,隱私是產品設計的核心:預設情況下,你的工作區內容只有你的帳號看得到。",
  ],
  sections: [
    {
      heading: "1. 我們蒐集的資訊",
      paragraphs: ["我們蒐集以下類別的資訊:"],
      list: [
        "帳號資料:你的電子郵件地址與驗證憑證(密碼僅由驗證服務商以密碼學雜湊形式保存)。",
        "工作區內容:你輸入或產生的人物、職務、組織、筆記、對話摘要、主題、待追蹤事項、談話重點與準備構想——其中可能包含其他人的個人資訊。敏感的工作區內容除傳輸加密外,另以 AES-256-GCM 加密儲存。",
        "偏好設定:你的語言選擇與方案資訊。",
        "帳單資料:你的方案、訂閱狀態與付款紀錄參照。卡號與完整付款資料由金流服務商直接蒐集與保存,我們不經手。",
        "技術資料:標準伺服器紀錄,例如 IP 位址、瀏覽器類型與時間戳記,用於安全性與穩定性維護。",
      ],
    },
    {
      heading: "2. 我們如何使用資訊",
      paragraphs: ["我們將蒐集到的資訊用於:"],
      list: [
        "提供本服務:儲存你的內容、在你的裝置間同步,並確保只有你的帳號看得到。",
        "依你的請求,使用你為該位人物保存的脈絡產生準備建議。",
        "處理付款並管理你的訂閱。",
        "維護服務安全、防止濫用並排查問題。",
        "就你的帳號、安全、帳單,以及產品或政策的重大變更與你溝通。",
        "履行法律義務。",
      ],
    },
    {
      heading: "3. AI 處理",
      paragraphs: [
        "當你要求本服務產生準備建議時,相關脈絡(例如你為該位人物保存的筆記與對話紀錄)會傳送給我們使用的 AI 模型供應商,僅用於回傳建議給你。我們與供應商的合約要求:你的內容不得用於訓練其模型。",
        "無論是否使用 AI 功能,請不要在本服務輸入高度敏感的資訊(禁止內容請見《服務條款》)。",
      ],
    },
    {
      heading: "4. 法律依據(歐洲經濟區、英國及類似地區)",
      paragraphs: [
        "在資料保護法要求具備法律依據時,我們基於下列依據處理個人資料:(a) 履行與你的契約(提供你註冊的服務);(b) 基於維護服務安全與改善服務的正當利益,並已衡平你的權利;(c) 在需要時取得你的同意;以及 (d) 履行法律義務。",
      ],
    },
    {
      heading: "5. 我們如何分享資訊",
      paragraphs: ["我們不出售你的個人資訊,僅與下列對象分享:"],
      list: [
        "代我們營運本服務的供應商:雲端託管與資料庫基礎設施、身分驗證、金流處理與 AI 模型供應商。各供應商僅取得執行其功能所需的資訊,並受契約保密與資料保護義務拘束。",
        "依法律、法律程序要求,或為保護本服務、使用者或他人的權利、安全而必須分享時的相關機關或當事人。",
        "因合併、收購或資產出售而承接業務者,並受本政策拘束。",
      ],
    },
    {
      heading: "6. 跨境傳輸",
      paragraphs: [
        "我們服務全球使用者,供應商可能在你所在國家以外的地方處理資料,各地法律可能不同。在法律要求時,我們採用公認的保護機制(例如標準契約條款)進行跨境傳輸。",
      ],
    },
    {
      heading: "7. 保存期間",
      paragraphs: [
        "帳號有效期間,我們會保存你的帳號資料與工作區內容。你刪除內容後,線上系統會立即移除,備份則依正常輪替週期清除。你可以在帳號頁自行刪除帳號——我們會在合理期間內刪除你的內容並取消任何有效中的付費訂閱,但法律要求較長保存期間者除外(例如付款紀錄)。",
      ],
    },
    {
      heading: "8. 安全性",
      paragraphs: [
        "我們採用傳輸與儲存加密、以帳號為單位的資料隔離,以及最小權限的存取控管。敏感的工作區內容(例如姓名、筆記、談話重點與職涯資訊)在儲存前另以 AES-256-GCM 於應用層加密。但任何傳輸或儲存方式都無法保證絕對安全;若發生影響你個人資料的外洩事件,我們會依法通知你與主管機關。",
      ],
    },
    {
      heading: "9. 你的權利",
      paragraphs: [
        "依你所在地法律(包括歐洲經濟區、英國、加州及其他地區),你可能享有存取、更正、匯出或刪除個人資料、反對或限制特定處理,以及撤回同意的權利。大多數權利你可以直接在本服務中行使:在工作區檢視、編輯與刪除內容,在帳號頁下載完整的 JSON 匯出檔,或永久刪除帳號(將一併刪除所有相關內容)。你也可以隨時聯絡我們。",
        "你也可以向當地資料保護主管機關提出申訴。加州居民:我們不出售個人資訊,也不為跨情境行為廣告目的分享個人資訊。",
      ],
    },
    {
      heading: "10. 關於他人的資訊",
      paragraphs: [
        "本服務允許你記錄你認識的人的相關資訊。就這些資訊,你是資料控制者,我們是依你指示行事的處理者:記錄什麼由你決定,你也必須具備合法依據、在需要時告知當事人,並回應他們的請求。若當事人直接向我們詢問你儲存的資訊,我們可能請他們與你聯絡,或請你代為回應。",
      ],
    },
    {
      heading: "11. Cookie",
      paragraphs: [
        "我們僅使用維持登入、保護連線安全與記住偏好設定所必需的 Cookie 與瀏覽器儲存空間,不使用廣告或第三方追蹤 Cookie。",
      ],
    },
    {
      heading: "12. 兒童",
      paragraphs: [
        "本服務不以未滿 18 歲者為對象,我們也不會明知而蒐集兒童的個人資訊。若你認為有兒童向我們提供了資訊,請聯絡我們,我們會將其刪除。",
      ],
    },
    {
      heading: "13. 本政策的變更",
      paragraphs: [
        "我們得不時更新本政策。更新後的版本會標示新的生效日期並公布於本服務;屬重大變更者,我們會事先以電子郵件或服務內通知。",
      ],
    },
  ],
  contactLabel: "對隱私或你的資料有疑問",
  contactEmail: LEGAL_CONTACT_EMAIL,
};

export const legalContent: Record<Locale, { terms: LegalDoc; privacy: LegalDoc }> = {
  en: { terms: termsEn, privacy: privacyEn },
  "zh-TW": { terms: termsZh, privacy: privacyZh },
};
